use latexsnipper_foundation::{Result, SnipperError};
use serde::{Deserialize, Serialize};
use std::path::Path;

/// Model configuration parsed from config.json.
/// Matches the format generated by scripts/package-models.js
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelConfig {
    pub model_type: String,
    #[serde(default)]
    pub model_family: Option<String>,
    #[serde(default)]
    pub license: Option<String>,

    /// Task type: detection, segmentation, ocr, classification, generation
    #[serde(default)]
    pub task_type: Option<String>,

    /// Number of classes (detection/classification models)
    #[serde(default)]
    pub num_classes: Option<u32>,

    /// Whether the model supports dynamic input shapes
    #[serde(default)]
    pub dynamic_shapes: Option<bool>,

    // For yolov8/dbnet/crnn_ctc: flat input/output
    #[serde(default)]
    pub input: Option<InputConfig>,
    #[serde(default)]
    pub output: Option<OutputConfig>,

    // For trocr: nested encoder/decoder
    #[serde(default)]
    pub encoder: Option<EncoderConfig>,
    #[serde(default)]
    pub decoder: Option<DecoderConfig>,

    #[serde(default)]
    pub preprocessing: Option<PreprocessConfig>,
    #[serde(default)]
    pub postprocessing: Option<PostprocessConfig>,
    #[serde(default)]
    pub decoding: Option<DecodingConfig>,

    /// Quantization information (INT8, FP16, etc.)
    #[serde(default)]
    pub quantization: Option<QuantizationConfig>,

    /// Additional outputs for multi-head models
    #[serde(default)]
    pub outputs: Option<Vec<OutputConfig>>,

    /// Extra metadata (flexible key-value for model-specific params)
    #[serde(default)]
    pub extra: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InputConfig {
    pub name: String,
    pub shape: Vec<i64>,
    pub dtype: String,
    /// Value range after normalization, e.g. [0.0, 1.0] or [-1.0, 1.0]
    #[serde(default)]
    pub range: Option<Vec<f32>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OutputConfig {
    pub name: String,
    pub shape: Vec<i64>,
    #[serde(default)]
    pub description: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EncoderConfig {
    pub input: InputConfig,
    pub output: OutputConfig,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DecoderConfig {
    pub input_ids: TensorConfig,
    pub encoder_hidden: TensorConfig,
    pub output: OutputConfig,
    #[serde(default)]
    pub max_length: Option<usize>,
    #[serde(default)]
    pub eos_token_id: Option<i64>,
    #[serde(default)]
    pub pad_token_id: Option<i64>,
    /// Vocabulary size
    #[serde(default)]
    pub vocab_size: Option<usize>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TensorConfig {
    pub name: String,
    #[serde(default)]
    pub dtype: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PreprocessConfig {
    #[serde(default)]
    pub resize: Option<ResizeConfig>,
    #[serde(default)]
    pub normalization: Option<NormalizationConfig>,
    #[serde(default)]
    pub color_format: Option<String>,
    #[serde(default)]
    pub divisible_by: Option<u32>,
    /// Padding value before normalization (e.g. 114 for YOLO letterbox)
    #[serde(default)]
    pub pad_value: Option<f32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResizeConfig {
    #[serde(default)]
    pub width: Option<u32>,
    #[serde(default)]
    pub height: Option<u32>,
    #[serde(default)]
    pub keep_ratio: Option<bool>,
    #[serde(default)]
    pub pad_value: Option<f32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NormalizationConfig {
    #[serde(default)]
    pub mean: Option<Vec<f32>>,
    #[serde(default)]
    pub std: Option<Vec<f32>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostprocessConfig {
    #[serde(rename = "type")]
    #[serde(default)]
    pub postprocess_type: Option<String>,
    #[serde(default)]
    pub confidence_threshold: Option<f32>,
    #[serde(default)]
    pub iou_threshold: Option<f32>,
    /// DBNet binary threshold
    #[serde(default)]
    pub threshold: Option<f32>,
    /// DBNet box score threshold
    #[serde(default)]
    pub box_threshold: Option<f32>,
    #[serde(default)]
    pub max_detections: Option<usize>,
    /// DBNet max contour candidates
    #[serde(default)]
    pub max_candidates: Option<usize>,
    #[serde(default)]
    pub unclip_ratio: Option<f32>,
    /// Anchor sizes for anchor-based detectors
    #[serde(default)]
    pub anchors: Option<Vec<Vec<[f32; 2]>>>,
    /// Stride per feature map level
    #[serde(default)]
    pub strides: Option<Vec<u32>>,
    /// DFL regression max (YOLOv8)
    #[serde(default)]
    pub reg_max: Option<u32>,
    /// DETR: number of object queries
    #[serde(default)]
    pub num_queries: Option<u32>,
    /// Apply sigmoid to class scores before thresholding (YOLOv8 with built-in sigmoid = false)
    #[serde(default)]
    pub apply_sigmoid: Option<bool>,
    /// Output tensor layout: "row_major" [N,6] or "col_major" [6,N]
    #[serde(default)]
    pub output_layout: Option<String>,
    /// Extra postprocessing params
    #[serde(default)]
    pub extra: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DecodingConfig {
    #[serde(rename = "type")]
    #[serde(default)]
    pub decoding_type: Option<String>,
    #[serde(default)]
    pub beam_width: Option<usize>,
    #[serde(default)]
    pub top_k: Option<usize>,
    #[serde(default)]
    pub blank_id: Option<usize>,
    #[serde(default)]
    pub tokenizer_file: Option<String>,
    #[serde(default)]
    pub keys_file: Option<String>,
    /// Temperature for sampling-based decoding
    #[serde(default)]
    pub temperature: Option<f32>,
    /// Top-p (nucleus) sampling threshold
    #[serde(default)]
    pub top_p: Option<f32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuantizationConfig {
    /// Quantization type: int8, fp16, bf16, mixed
    #[serde(default)]
    pub quant_type: Option<String>,
    /// Whether the model is quantized
    #[serde(default)]
    pub is_quantized: Option<bool>,
    /// Accuracy loss percentage compared to FP32
    #[serde(default)]
    pub accuracy_loss_pct: Option<f32>,
    /// Original FP32 model size in bytes
    #[serde(default)]
    pub original_size_bytes: Option<u64>,
    /// Quantized model size in bytes
    #[serde(default)]
    pub quantized_size_bytes: Option<u64>,
}

impl ModelConfig {
    /// Load config.json from a model directory.
    pub fn load(model_dir: &Path) -> Result<Self> {
        let config_path = model_dir.join("config.json");
        let content = std::fs::read_to_string(&config_path).map_err(|e| {
            SnipperError::Model(format!("Failed to read {}: {}", config_path.display(), e))
        })?;
        Self::parse(&content)
    }

    /// Parse config.json from a string.
    pub fn parse(json: &str) -> Result<Self> {
        serde_json::from_str(json)
            .map_err(|e| SnipperError::Model(format!("Invalid config.json: {}", e)))
    }

    /// Build a minimal config for Paddle inference packages.
    /// These packages still need an ONNX export before the ONNX runtime can execute them.
    pub fn from_paddle_inference_dir(model_dir: &Path) -> Result<Self> {
        let yml_path = model_dir.join("inference.yml");
        if !yml_path.exists() {
            return Err(SnipperError::Model(format!(
                "Paddle inference.yml not found in {}",
                model_dir.display()
            )));
        }

        Ok(Self {
            model_type: "crnn_ctc".into(),
            model_family: Some("PaddleOCRv6 Text Recognition".into()),
            license: None,
            task_type: Some("ocr".into()),
            num_classes: None,
            dynamic_shapes: Some(true),
            input: Some(InputConfig {
                name: "x".into(),
                shape: vec![1, 3, 48, 3200],
                dtype: "float32".into(),
                range: Some(vec![0.0, 1.0]),
            }),
            output: Some(OutputConfig {
                name: "fetch_name_0".into(),
                shape: vec![1, -1, -1],
                description: Some("CTC probabilities from PaddleOCRv6".into()),
            }),
            encoder: None,
            decoder: None,
            preprocessing: Some(PreprocessConfig {
                resize: Some(ResizeConfig {
                    width: Some(3200),
                    height: Some(48),
                    keep_ratio: Some(true),
                    pad_value: Some(0.0),
                }),
                normalization: Some(NormalizationConfig {
                    mean: Some(vec![0.5, 0.5, 0.5]),
                    std: Some(vec![0.5, 0.5, 0.5]),
                }),
                color_format: Some("BGR".into()),
                divisible_by: None,
                pad_value: Some(0.0),
            }),
            postprocessing: None,
            decoding: Some(DecodingConfig {
                decoding_type: Some("ctc_greedy".into()),
                beam_width: None,
                top_k: None,
                blank_id: Some(0),
                tokenizer_file: None,
                keys_file: Some("inference.yml".into()),
                temperature: None,
                top_p: None,
            }),
            quantization: None,
            outputs: None,
            extra: None,
        })
    }

    /// Find the main ONNX model file in a directory.
    pub fn find_model_file(&self, model_dir: &Path) -> Option<std::path::PathBuf> {
        let candidates = ["model.onnx", "model_int8.onnx"];
        for name in &candidates {
            let path = model_dir.join(name);
            if path.exists() {
                return Some(path);
            }
        }
        std::fs::read_dir(model_dir).ok().and_then(|entries| {
            entries
                .filter_map(|e| e.ok())
                .find(|e| e.path().extension().is_some_and(|ext| ext == "onnx"))
                .map(|e| e.path())
        })
    }

    /// Find encoder ONNX file (for TrOCR models).
    pub fn find_encoder_file(&self, model_dir: &Path) -> Option<std::path::PathBuf> {
        let candidates = ["encoder_model.onnx", "encoder.onnx"];
        for name in &candidates {
            let path = model_dir.join(name);
            if path.exists() {
                return Some(path);
            }
        }
        None
    }

    /// Find decoder ONNX file (for TrOCR models).
    pub fn find_decoder_file(&self, model_dir: &Path) -> Option<std::path::PathBuf> {
        let candidates = ["decoder_model.onnx", "decoder.onnx"];
        for name in &candidates {
            let path = model_dir.join(name);
            if path.exists() {
                return Some(path);
            }
        }
        None
    }

    /// Find tokenizer file.
    pub fn find_tokenizer_file(&self, model_dir: &Path) -> Option<std::path::PathBuf> {
        if let Some(decoding) = &self.decoding {
            for configured in [
                decoding.tokenizer_file.as_deref(),
                decoding.keys_file.as_deref(),
            ]
            .into_iter()
            .flatten()
            {
                let path = model_dir.join(configured);
                if path.exists() {
                    return Some(path);
                }
            }
        }

        let candidates = [
            "tokenizer.json",
            "ppocrv6_keys.txt",
            "ppocrv5_keys.txt",
            "ppocr_keys.txt",
            "dict.txt",
            "inference.yml",
        ];
        for name in &candidates {
            let path = model_dir.join(name);
            if path.exists() {
                return Some(path);
            }
        }
        None
    }

    /// Get normalization mean values from preprocessing config.
    pub fn normalization_mean(&self) -> Vec<f32> {
        if let Some(ref pre) = self.preprocessing {
            if let Some(ref norm) = pre.normalization {
                if let Some(ref mean) = norm.mean {
                    return mean.clone();
                }
            }
        }
        vec![0.0, 0.0, 0.0]
    }

    /// Get normalization std values from preprocessing config.
    pub fn normalization_std(&self) -> Vec<f32> {
        if let Some(ref pre) = self.preprocessing {
            if let Some(ref norm) = pre.normalization {
                if let Some(ref std) = norm.std {
                    return std.clone();
                }
            }
        }
        vec![255.0, 255.0, 255.0]
    }

    /// Get resize dimensions from preprocessing config.
    pub fn resize_dimensions(&self) -> (Option<u32>, Option<u32>) {
        if let Some(ref pre) = self.preprocessing {
            if let Some(ref resize) = pre.resize {
                return (resize.width, resize.height);
            }
        }
        (None, None)
    }

    /// Get color format (RGB or BGR).
    pub fn color_format(&self) -> &str {
        self.preprocessing
            .as_ref()
            .and_then(|p| p.color_format.as_deref())
            .unwrap_or("RGB")
    }

    /// Check if model uses dynamic input shapes.
    pub fn has_dynamic_shapes(&self) -> bool {
        self.dynamic_shapes.unwrap_or(false)
    }

    /// Get the model's primary task type.
    pub fn task_type(&self) -> &str {
        self.task_type
            .as_deref()
            .unwrap_or(match self.model_type.as_str() {
                "yolov8" => "detection",
                "dbnet" => "detection",
                "trocr" => "ocr",
                "crnn_ctc" => "ocr",
                "pplcnet" => "classification",
                _ => "unknown",
            })
    }
}
