use latexsnipper_foundation::{Result, SnipperError};
use serde::{Deserialize, Serialize};
use std::fmt;
use std::path::Path;

/// DBNet output box type: quad (4-point polygon) or poly (full contour).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DbNetBoxType {
    Quad,
    Poly,
}

impl Default for DbNetBoxType {
    fn default() -> Self {
        Self::Quad
    }
}

impl fmt::Display for DbNetBoxType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Quad => write!(f, "quad"),
            Self::Poly => write!(f, "poly"),
        }
    }
}

/// DBNet box score calculation mode: fast (bounding-box mask) or slow (polygon mask).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DbNetScoreMode {
    Fast,
    Slow,
}

impl Default for DbNetScoreMode {
    fn default() -> Self {
        Self::Fast
    }
}

impl fmt::Display for DbNetScoreMode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Fast => write!(f, "fast"),
            Self::Slow => write!(f, "slow"),
        }
    }
}

/// CTC output tensor layout: ntc (batch, time, channel) or tnc (time, batch, channel).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum CtcOutputLayout {
    Ntc,
    Tnc,
}

impl Default for CtcOutputLayout {
    fn default() -> Self {
        Self::Ntc
    }
}

impl fmt::Display for CtcOutputLayout {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Ntc => write!(f, "ntc"),
            Self::Tnc => write!(f, "tnc"),
        }
    }
}

/// Type of logits in CTC output tensor.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LogitsKind {
    Logits,
    Probabilities,
    LogProbabilities,
}

impl Default for LogitsKind {
    fn default() -> Self {
        Self::Logits
    }
}

impl fmt::Display for LogitsKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Logits => write!(f, "logits"),
            Self::Probabilities => write!(f, "probabilities"),
            Self::LogProbabilities => write!(f, "log_probabilities"),
        }
    }
}

/// Model configuration parsed from config.json.
/// Matches the format generated by scripts/package-models.js
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelConfig {
    pub model_type: String,
    #[serde(default)]
    pub model_family: Option<String>,
    #[serde(default)]
    pub license: Option<String>,

    /// Task type: detection, segmentation, ocr, classification, generation
    #[serde(default)]
    pub task_type: Option<String>,

    /// Number of classes (detection/classification models)
    #[serde(default)]
    pub num_classes: Option<u32>,

    /// Whether the model supports dynamic input shapes
    #[serde(default)]
    pub dynamic_shapes: Option<bool>,

    // For yolov8/dbnet/crnn_ctc: flat input/output
    #[serde(default)]
    pub input: Option<InputConfig>,
    #[serde(default)]
    pub output: Option<OutputConfig>,

    // For trocr: nested encoder/decoder
    #[serde(default)]
    pub encoder: Option<EncoderConfig>,
    #[serde(default)]
    pub decoder: Option<DecoderConfig>,

    #[serde(default)]
    pub preprocessing: Option<PreprocessConfig>,
    #[serde(default)]
    pub postprocessing: Option<PostprocessConfig>,
    #[serde(default)]
    pub decoding: Option<DecodingConfig>,

    /// Quantization information (INT8, FP16, etc.)
    #[serde(default)]
    pub quantization: Option<QuantizationConfig>,

    /// Additional outputs for multi-head models
    #[serde(default)]
    pub outputs: Option<Vec<OutputConfig>>,

    /// Extra metadata (flexible key-value for model-specific params)
    #[serde(default)]
    pub extra: Option<serde_json::Value>,

    /// Pipeline-specific configuration — tells the pipeline how to use this model.
    #[serde(default)]
    pub pipeline: Option<PipelineConfig>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InputConfig {
    pub name: String,
    pub shape: Vec<i64>,
    pub dtype: String,
    /// Value range after normalization, e.g. [0.0, 1.0] or [-1.0, 1.0]
    #[serde(default)]
    pub range: Option<Vec<f32>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OutputConfig {
    pub name: String,
    pub shape: Vec<i64>,
    #[serde(default)]
    pub description: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EncoderConfig {
    pub input: InputConfig,
    pub output: OutputConfig,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DecoderConfig {
    pub input_ids: TensorConfig,
    pub encoder_hidden: TensorConfig,
    pub output: OutputConfig,
    #[serde(default)]
    pub max_length: Option<usize>,
    #[serde(default)]
    pub eos_token_id: Option<i64>,
    #[serde(default)]
    pub pad_token_id: Option<i64>,
    /// Vocabulary size
    #[serde(default)]
    pub vocab_size: Option<usize>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TensorConfig {
    pub name: String,
    #[serde(default)]
    pub dtype: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PreprocessConfig {
    #[serde(default)]
    pub resize: Option<ResizeConfig>,
    #[serde(default)]
    pub normalization: Option<NormalizationConfig>,
    #[serde(default)]
    pub color_format: Option<String>,
    #[serde(default)]
    pub divisible_by: Option<u32>,
    /// Padding value before normalization (e.g. 114 for YOLO letterbox)
    #[serde(default)]
    pub pad_value: Option<f32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResizeConfig {
    #[serde(default)]
    pub width: Option<u32>,
    #[serde(default)]
    pub height: Option<u32>,
    #[serde(default)]
    pub keep_ratio: Option<bool>,
    #[serde(default)]
    pub pad_value: Option<f32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NormalizationConfig {
    #[serde(default)]
    pub mean: Option<Vec<f32>>,
    #[serde(default)]
    pub std: Option<Vec<f32>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostprocessConfig {
    #[serde(rename = "type")]
    #[serde(default)]
    pub postprocess_type: Option<String>,
    #[serde(default)]
    pub confidence_threshold: Option<f32>,
    #[serde(default)]
    pub iou_threshold: Option<f32>,
    /// DBNet binary threshold
    #[serde(default)]
    pub threshold: Option<f32>,
    /// DBNet box score threshold
    #[serde(default)]
    pub box_threshold: Option<f32>,
    #[serde(default)]
    pub max_detections: Option<usize>,
    /// DBNet max contour candidates
    #[serde(default)]
    pub max_candidates: Option<usize>,
    #[serde(default)]
    pub unclip_ratio: Option<f32>,
    /// DBNet output box type: "quad" or "poly"
    #[serde(default)]
    pub box_type: Option<DbNetBoxType>,
    /// DBNet score mode: "fast" (bbox mask) or "slow" (polygon mask)
    #[serde(default)]
    pub score_mode: Option<DbNetScoreMode>,
    /// Anchor sizes for anchor-based detectors
    #[serde(default)]
    pub anchors: Option<Vec<Vec<[f32; 2]>>>,
    /// Stride per feature map level
    #[serde(default)]
    pub strides: Option<Vec<u32>>,
    /// DFL regression max (YOLOv8)
    #[serde(default)]
    pub reg_max: Option<u32>,
    /// DETR: number of object queries
    #[serde(default)]
    pub num_queries: Option<u32>,
    /// Apply sigmoid to class scores before thresholding (YOLOv8 with built-in sigmoid = false)
    #[serde(default)]
    pub apply_sigmoid: Option<bool>,
    /// Output tensor layout: "row_major" [N,6] or "col_major" [6,N]
    #[serde(default)]
    pub output_layout: Option<String>,
    /// Extra postprocessing params
    #[serde(default)]
    pub extra: Option<serde_json::Value>,
}

impl PostprocessConfig {
    /// Get DBNet box type, defaulting to Quad.
    pub fn dbnet_box_type(&self) -> DbNetBoxType {
        self.box_type.unwrap_or_default()
    }

    /// Get DBNet score mode, defaulting to Fast.
    pub fn dbnet_score_mode(&self) -> DbNetScoreMode {
        self.score_mode.unwrap_or_default()
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DecodingConfig {
    #[serde(rename = "type")]
    #[serde(default)]
    pub decoding_type: Option<String>,
    #[serde(default)]
    pub beam_width: Option<usize>,
    #[serde(default)]
    pub top_k: Option<usize>,
    #[serde(default)]
    pub blank_id: Option<usize>,
    /// CTC output tensor layout: "ntc" or "tnc"
    #[serde(default)]
    pub output_layout: Option<CtcOutputLayout>,
    /// Type of logits in CTC output: "logits", "probabilities", or "log_probabilities"
    #[serde(default)]
    pub logits_kind: Option<LogitsKind>,
    #[serde(default)]
    pub tokenizer_file: Option<String>,
    #[serde(default)]
    pub keys_file: Option<String>,
    /// Temperature for sampling-based decoding
    #[serde(default)]
    pub temperature: Option<f32>,
    /// Top-p (nucleus) sampling threshold
    #[serde(default)]
    pub top_p: Option<f32>,
}

impl DecodingConfig {
    /// Get CTC output layout, defaulting to Ntc.
    pub fn ctc_output_layout(&self) -> CtcOutputLayout {
        self.output_layout.unwrap_or_default()
    }

    /// Get logits kind, defaulting to Logits.
    pub fn ctc_logits_kind(&self) -> LogitsKind {
        self.logits_kind.unwrap_or_default()
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuantizationConfig {
    /// Quantization type: int8, fp16, bf16, mixed
    #[serde(default)]
    pub quant_type: Option<String>,
    /// Whether the model is quantized
    #[serde(default)]
    pub is_quantized: Option<bool>,
    /// Accuracy loss percentage compared to FP32
    #[serde(default)]
    pub accuracy_loss_pct: Option<f32>,
    /// Original FP32 model size in bytes
    #[serde(default)]
    pub original_size_bytes: Option<u64>,
    /// Quantized model size in bytes
    #[serde(default)]
    pub quantized_size_bytes: Option<u64>,
}

/// Pipeline configuration — tells the pipeline how to use this model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PipelineConfig {
    /// Detection filter: minimum area in pixels
    #[serde(default)]
    pub min_area: Option<f32>,
    /// Detection filter: minimum confidence threshold
    #[serde(default)]
    pub min_confidence: Option<f32>,
    /// Detection filter: maximum number of detections
    #[serde(default)]
    pub max_detections: Option<usize>,
    /// Model files to load (relative to model dir)
    #[serde(default)]
    pub model_files: Option<ModelFiles>,
    /// Fallback model directories (for models with multiple versions)
    #[serde(default)]
    pub fallback_dirs: Option<Vec<String>>,
    /// Additional model-specific parameters
    #[serde(default)]
    pub params: Option<serde_json::Value>,
}

/// Model file paths relative to the model directory.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelFiles {
    /// Primary model file (e.g., "model.onnx", "mathcraft-mfd.onnx")
    #[serde(default)]
    pub primary: Option<String>,
    /// Encoder model (for encoder-decoder models like TrOCR)
    #[serde(default)]
    pub encoder: Option<String>,
    /// Decoder model
    #[serde(default)]
    pub decoder: Option<String>,
    /// Tokenizer/keys file
    #[serde(default)]
    pub tokenizer: Option<String>,
}

impl ModelConfig {
    /// Load config.json from a model directory.
    pub fn load(model_dir: &Path) -> Result<Self> {
        let config_path = model_dir.join("config.json");
        let content = std::fs::read_to_string(&config_path).map_err(|e| {
            SnipperError::Model(format!("Failed to read {}: {}", config_path.display(), e))
        })?;
        Self::parse(&content)
    }

    /// Parse config.json from a string.
    pub fn parse(json: &str) -> Result<Self> {
        serde_json::from_str(json)
            .map_err(|e| SnipperError::Model(format!("Invalid config.json: {}", e)))
    }

    /// Create a minimal config with default values.
    ///
    /// Used when no config.json exists but a model needs to be loaded.
    pub fn minimal() -> Self {
        Self {
            model_type: "unknown".into(),
            model_family: None,
            license: None,
            task_type: None,
            num_classes: None,
            dynamic_shapes: None,
            input: None,
            output: None,
            encoder: None,
            decoder: None,
            preprocessing: None,
            postprocessing: None,
            decoding: None,
            quantization: None,
            outputs: None,
            extra: None,
            pipeline: None,
        }
    }

    /// Build a minimal config for Paddle inference packages.
    /// These packages still need an ONNX export before the ONNX runtime can execute them.
    pub fn from_paddle_inference_dir(model_dir: &Path) -> Result<Self> {
        let yml_path = model_dir.join("inference.yml");
        if !yml_path.exists() {
            return Err(SnipperError::Model(format!(
                "Paddle inference.yml not found in {}",
                model_dir.display()
            )));
        }

        Ok(Self {
            model_type: "crnn_ctc".into(),
            model_family: Some("PaddleOCRv6 Text Recognition".into()),
            license: None,
            task_type: Some("ocr".into()),
            num_classes: None,
            dynamic_shapes: Some(true),
            input: Some(InputConfig {
                name: "x".into(),
                shape: vec![1, 3, 48, 3200],
                dtype: "float32".into(),
                range: Some(vec![0.0, 1.0]),
            }),
            output: Some(OutputConfig {
                name: "fetch_name_0".into(),
                shape: vec![1, -1, -1],
                description: Some("CTC probabilities from PaddleOCRv6".into()),
            }),
            encoder: None,
            decoder: None,
            preprocessing: Some(PreprocessConfig {
                resize: Some(ResizeConfig {
                    width: Some(3200),
                    height: Some(48),
                    keep_ratio: Some(true),
                    pad_value: Some(0.0),
                }),
                normalization: Some(NormalizationConfig {
                    mean: Some(vec![0.5, 0.5, 0.5]),
                    std: Some(vec![0.5, 0.5, 0.5]),
                }),
                color_format: Some("BGR".into()),
                divisible_by: None,
                pad_value: Some(0.0),
            }),
            postprocessing: None,
            decoding: Some(DecodingConfig {
                decoding_type: Some("ctc_greedy".into()),
                beam_width: None,
                top_k: None,
                blank_id: Some(0),
                output_layout: None,
                logits_kind: None,
                tokenizer_file: None,
                keys_file: Some("inference.yml".into()),
                temperature: None,
                top_p: None,
            }),
            quantization: None,
            outputs: None,
            extra: None,
            pipeline: None,
        })
    }

    /// Find the main ONNX model file in a directory.
    pub fn find_model_file(&self, model_dir: &Path) -> Option<std::path::PathBuf> {
        let candidates = ["model.onnx", "model_int8.onnx"];
        for name in &candidates {
            let path = model_dir.join(name);
            if path.exists() {
                return Some(path);
            }
        }
        std::fs::read_dir(model_dir).ok().and_then(|entries| {
            entries
                .filter_map(|e| e.ok())
                .find(|e| e.path().extension().is_some_and(|ext| ext == "onnx"))
                .map(|e| e.path())
        })
    }

    /// Find encoder ONNX file (for TrOCR models).
    pub fn find_encoder_file(&self, model_dir: &Path) -> Option<std::path::PathBuf> {
        let candidates = ["encoder_model.onnx", "encoder.onnx"];
        for name in &candidates {
            let path = model_dir.join(name);
            if path.exists() {
                return Some(path);
            }
        }
        None
    }

    /// Find decoder ONNX file (for TrOCR models).
    pub fn find_decoder_file(&self, model_dir: &Path) -> Option<std::path::PathBuf> {
        let candidates = ["decoder_model.onnx", "decoder.onnx"];
        for name in &candidates {
            let path = model_dir.join(name);
            if path.exists() {
                return Some(path);
            }
        }
        None
    }

    /// Find tokenizer file.
    pub fn find_tokenizer_file(&self, model_dir: &Path) -> Option<std::path::PathBuf> {
        if let Some(decoding) = &self.decoding {
            for configured in [
                decoding.tokenizer_file.as_deref(),
                decoding.keys_file.as_deref(),
            ]
            .into_iter()
            .flatten()
            {
                let path = model_dir.join(configured);
                if path.exists() {
                    return Some(path);
                }
            }
        }

        let candidates = [
            "tokenizer.json",
            "ppocrv6_keys.txt",
            "ppocrv5_keys.txt",
            "ppocr_keys.txt",
            "dict.txt",
            "inference.yml",
        ];
        for name in &candidates {
            let path = model_dir.join(name);
            if path.exists() {
                return Some(path);
            }
        }
        None
    }

    /// Get normalization mean values from preprocessing config.
    pub fn normalization_mean(&self) -> Vec<f32> {
        if let Some(ref pre) = self.preprocessing {
            if let Some(ref norm) = pre.normalization {
                if let Some(ref mean) = norm.mean {
                    return mean.clone();
                }
            }
        }
        vec![0.0, 0.0, 0.0]
    }

    /// Get normalization std values from preprocessing config.
    pub fn normalization_std(&self) -> Vec<f32> {
        if let Some(ref pre) = self.preprocessing {
            if let Some(ref norm) = pre.normalization {
                if let Some(ref std) = norm.std {
                    return std.clone();
                }
            }
        }
        vec![255.0, 255.0, 255.0]
    }

    /// Get resize dimensions from preprocessing config.
    pub fn resize_dimensions(&self) -> (Option<u32>, Option<u32>) {
        if let Some(ref pre) = self.preprocessing {
            if let Some(ref resize) = pre.resize {
                return (resize.width, resize.height);
            }
        }
        (None, None)
    }

    /// Get color format (RGB or BGR).
    pub fn color_format(&self) -> &str {
        self.preprocessing
            .as_ref()
            .and_then(|p| p.color_format.as_deref())
            .unwrap_or("RGB")
    }

    /// Check if model uses dynamic input shapes.
    pub fn has_dynamic_shapes(&self) -> bool {
        self.dynamic_shapes.unwrap_or(false)
    }

    /// Get the model's primary task type.
    pub fn task_type(&self) -> &str {
        self.task_type
            .as_deref()
            .unwrap_or(match self.model_type.as_str() {
                "yolov8" => "detection",
                "dbnet" => "detection",
                "trocr" => "ocr",
                "crnn_ctc" => "ocr",
                "pplcnet" => "classification",
                _ => "unknown",
            })
    }

    /// Get minimum area filter from pipeline config.
    pub fn pipeline_min_area(&self) -> f32 {
        self.pipeline
            .as_ref()
            .and_then(|p| p.min_area)
            .unwrap_or(100.0)
    }

    /// Get minimum confidence filter from pipeline config.
    pub fn pipeline_min_confidence(&self) -> f32 {
        self.pipeline
            .as_ref()
            .and_then(|p| p.min_confidence)
            .unwrap_or(0.2)
    }

    /// Get the primary model file path from pipeline config.
    pub fn pipeline_model_path(&self, model_dir: &Path) -> Option<std::path::PathBuf> {
        if let Some(files) = self.pipeline.as_ref().and_then(|p| p.model_files.as_ref()) {
            if let Some(primary) = &files.primary {
                let path = model_dir.join(primary);
                if path.exists() {
                    return Some(path);
                }
            }
        }
        self.find_model_file(model_dir)
    }

    /// Get the encoder model file path from pipeline config.
    pub fn pipeline_encoder_path(&self, model_dir: &Path) -> Option<std::path::PathBuf> {
        if let Some(files) = self.pipeline.as_ref().and_then(|p| p.model_files.as_ref()) {
            if let Some(encoder) = &files.encoder {
                let path = model_dir.join(encoder);
                if path.exists() {
                    return Some(path);
                }
            }
        }
        self.find_encoder_file(model_dir)
    }

    /// Get the decoder model file path from pipeline config.
    pub fn pipeline_decoder_path(&self, model_dir: &Path) -> Option<std::path::PathBuf> {
        if let Some(files) = self.pipeline.as_ref().and_then(|p| p.model_files.as_ref()) {
            if let Some(decoder) = &files.decoder {
                let path = model_dir.join(decoder);
                if path.exists() {
                    return Some(path);
                }
            }
        }
        self.find_decoder_file(model_dir)
    }

    /// Get the tokenizer file path from pipeline config.
    pub fn pipeline_tokenizer_path(&self, model_dir: &Path) -> Option<std::path::PathBuf> {
        if let Some(files) = self.pipeline.as_ref().and_then(|p| p.model_files.as_ref()) {
            if let Some(tokenizer) = &files.tokenizer {
                let path = model_dir.join(tokenizer);
                if path.exists() {
                    return Some(path);
                }
            }
        }
        self.find_tokenizer_file(model_dir)
    }

    /// Get fallback directories from pipeline config.
    pub fn pipeline_fallback_dirs(&self, models_dir: &Path) -> Vec<std::path::PathBuf> {
        self.pipeline
            .as_ref()
            .and_then(|p| p.fallback_dirs.as_ref())
            .map(|dirs| dirs.iter().map(|d| models_dir.join(d)).collect())
            .unwrap_or_default()
    }

    /// Discover all models in a category directory.
    /// Returns Vec of (variant_name, ModelConfig, variant_dir) tuples,
    /// sorted alphabetically by variant name for deterministic selection.
    pub fn discover_all(
        models_dir: &Path,
        category: &str,
    ) -> Vec<(String, ModelConfig, std::path::PathBuf)> {
        let cat_dir = models_dir.join(category);
        if !cat_dir.is_dir() {
            return Vec::new();
        }

        let mut variants: Vec<(String, ModelConfig, std::path::PathBuf)> = Vec::new();

        for entry in std::fs::read_dir(&cat_dir).into_iter().flatten() {
            let Ok(entry) = entry else { continue };
            if !entry.path().is_dir() {
                continue;
            }
            let dir = entry.path();
            let Some(variant) = dir.file_name().and_then(|n| n.to_str()) else {
                continue;
            };
            let config = if dir.join("config.json").exists() {
                match ModelConfig::load(&dir) {
                    Ok(c) => c,
                    Err(_) => continue,
                }
            } else {
                match ModelConfig::from_paddle_inference_dir(&dir) {
                    Ok(c) => c,
                    Err(_) => continue,
                }
            };
            variants.push((variant.to_string(), config, dir));
        }

        // Deterministic: alphabetical by variant name
        variants.sort_by(|a, b| a.0.cmp(&b.0));
        variants
    }

    /// Find the best model in a category, trying variants in order.
    /// Returns (ModelConfig, model_file_path, variant_dir).
    pub fn find_best(
        models_dir: &Path,
        category: &str,
    ) -> Option<(ModelConfig, std::path::PathBuf, std::path::PathBuf)> {
        let variants = Self::discover_all(models_dir, category);
        for (_variant, config, variant_dir) in variants {
            if let Some(path) = config.pipeline_model_path(&variant_dir) {
                return Some((config, path, variant_dir));
            }
        }
        None
    }
}
